CREATE DATABASE TASK;
USE TASK;

CREATE TABLE EMPLOYEES(
EMPLOYEEID VARCHAR(5) PRIMARY KEY,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PHONENUMBER BIGINT UNIQUE,
HIREDATE DATE NOT NULL,
JOBTITLE VARCHAR(50) NOT NULL,
DEPARTMENT VARCHAR(20) NOT NULL,
SALARY DECIMAL(10,2) CHECK (SALARY > 0),
WORKINGSTATUS VARCHAR(20)
);

INSERT INTO EMPLOYEES 
(EMPLOYEEID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, HIREDATE, JOBTITLE, DEPARTMENT, SALARY, WORKINGSTATUS)
VALUES
('E001','VINODH','PALLI','vinodh@gmail.com',7995231195,'2026-04-01','MANAGER','HR',70000,'WORKING'),
('E002','DURGA','KAGITHALA','durga@gmail.com',9876543211,'2026-04-01','ACCOUNTANT','FINANCE',60000,'WORKING'),
('E003','CHANDU','DASARI','chandu@gmail.com',9567387654,'2024-04-01','DA','IT',65000,'WORKING'),
('E004','KAIF','MOHAMAD','kaif@gmail.com',7568943276,'2024-04-01','MANAGER','HR',70000,'WORKING'),
('E005','SANATH','SURYA','sanath@gmail.com',6453728190,'2020-04-01','ACCOUNTANT','FINANCE',60000,'OLD EMPLOYEE'),
('E006','RAM','KAMODULA','ram@gmail.com',7658493097,'2026-04-01','DA','IT',65000,'WORKING'),
('E007','SRIDHAR','DUNNA','sridhar@gmail.com',9003408793,'2020-04-01','MANAGER','HR',70000,'OLD EMPLOYEE'),
('E008','SAI','PALLI','sai@gmail.com',6309803879,'2020-04-01','DA','IT',67000,'OLD EMPLOYEE'),
('E009','PRABHA','IJJADA','prabha@gmail.com',9957634633,'2026-04-01','ACCOUNTANT','FINANCE',70000,'WORKING'),
('E010','PRAKASH','PALLI','prakash@gmail.com',7597809352,'2021-04-01','ACCOUNTANT','FINANCE',65000,'OLD EMPLOYEE');

-- AGGREGATE FUNCTIONS
-- COUNT EMPLOYEES BY DEPATMENT
SELECT DEPARTMENT,COUNT(*) AS EMPLOYEESCOUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- MIN() SALARY OF COMPANY
SELECT MIN(SALARY) AS MINIMUMSALARY 
FROM EMPLOYEES;

-- TOTAL AND AVERAGE SALARY OF IT DEPARTMENT
SELECT DEPARTMENT, SUM(SALARY) AS TOTALSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING DEPARTMENT='IT';

SELECT DEPARTMENT, AVG(SALARY) AS TOTALSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING DEPARTMENT='IT';

-- TOTAL SALARY OF DEPARTMENT EXCEEDS 100000

SELECT DEPARTMENT ,SUM(SALARY) AS TOATLSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>100000;

-- DEPARTMENT HAVING HEIGHEST AVERAGE SALARY
SELECT DEPARTMENT,AVG(SALARY) AS AVGSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY AVGSALARY DESC
LIMIT 1; 

-- TOTAL SALRY BY EACH DEPARTMENT
SELECT DEPARTMENT ,SUM(SALARY) AS TOTALSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

-- AVG SALARY OF DEPARTMENT GRETER THAN 50000
SELECT DEPARTMENT ,AVG(SALARY) AS AVGSALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVGSALARY>50000;

-- STRING FUNCTIONS

-- CONCAT
SELECT EMPLOYEEID,CONCAT(FIRSTNAME,' ',LASTNAME) AS FULLNAME
FROM EMPLOYEES;

SELECT LOWER(DEPARTMENT) AS LOWERDEPT,
UCASE(FIRSTNAME) AS UPPERNAME
FROM EMPLOYEES;


-- LENGTH OF FULL NAME
SELECT CONCAT(FIRSTNAME,' ',LASTNAME) AS FULLNAME,
LENGTH(CONCAT(FIRSTNAME,' ',LASTNAME)) AS LENGTHFULLNAME
FROM EMPLOYEES;

-- FIRST THREE LETTERS
SELECT JOBTITLE ,
SUBSTRING(JOBTITLE,1,3) AS SHORTNAME
FROM EMPLOYEES;

-- REPLACE
SELECT JOBTITLE,REPLACE(JOBTITLE,'ACCOUNTANT','FINANCE') AS MODIFIED
FROM EMPLOYEES;

-- DATE AND TIME FUNCTIONS

SELECT 
YEAR(HIREDATE)  AS YEAR,
MONTH(HIREDATE) AS MONTH,
DAY(HIREDATE)   AS DAY
FROM EMPLOYEES;

-- DATE DIFFERENCE
SELECT 
HIREDATE,DATEDIFF(CURDATE(), HIREDATE) AS DAYS_DIFF
FROM EMPLOYEES;

-- ADD 3 MONTHS
SELECT HIREDATE, ADDDATE(HIREDATE, INTERVAL 3 MONTH) AS NEWDATE
FROM EMPLOYEES;

-- SYSTEM TIME

SELECT SYSDATE() AS SYSTEMDATE;

-- CASE STATEMENT

-- SALARY CLASIFICATION

SELECT EMPLOYEEID, FIRSTNAME,SALARY,
CASE
WHEN SALARY < 30000 THEN 'LOW'
WHEN SALARY BETWEEN 30000 AND 70000 THEN 'MEDIUM'
ELSE 'HIGH'
END AS SALARYLEVEL
FROM EMPLOYEES;

-- EXPERIENCE CATEGORY

SELECT EMPLOYEEID,FIRSTNAME,HIREDATE,
CASE
WHEN HIREDATE < 2020-01-01 THEN 'EXPERIENCED'
WHEN HIREDATE BETWEEN 2020-01-01 AND 2021-01-01 THEN 'MID-LEVEL'
ELSE 'FRESHER'
END AS EXPERIENCECATEGORY
FROM EMPLOYEES;

-- OREDER 

SELECT DEPARTMENT,COUNT(*) AS EMP_COUNT
FROM EMPLOYEES
WHERE HIREDATE > '2022-01-01'
GROUP BY DEPARTMENT
HAVING COUNT(*) > 2
ORDER BY EMP_COUNT DESC
LIMIT 2;






 