CREATE DATABASE STUDENTDB;
USE STUDENTDB;

CREATE TABLE STUDENT(
STUDENTID CHAR(4),
NAME VARCHAR(50),
MARKS int
);

INSERT INTO STUDENT VALUES
('S001','RAM',90),
('S002','RAVI',80),
('S003','KARAN',70),
('S004','MEENA',60),
('S005','RIYA',50),
('S006','PRIYA',40);

-- SIMPLE CASE STATEMENT

SELECT 
STUDENTID,NAME,MARKS,
CASE MARKS
WHEN 90 THEN "OUTSTANDING"
WHEN 80 THEN "EXCELLENT"
WHEN 70 THEN "VERYGOOD"
WHEN 60 THEN "GOOD"
WHEN 50 THEN "PASS"
ELSE "FAIL"
END AS REMARK
FROM STUDENT;

-- SEARCH CASE STATEMENT

CREATE DATABASE STUDENTDB2;
USE STUDENTDB2;

CREATE TABLE STUDENT(
STUDENTID CHAR(4),
NAME VARCHAR(50),
MARKS int
);

INSERT INTO STUDENT VALUES
('S001','RAM',92),
('S002','RAVI',84),
('S003','KARAN',78),
('S004','MEENA',67),
('S005','RIYA',55),
('S006','PRIYA',40);

SELECT STUDENTID ,NAME,MARKS,
CASE
WHEN MARKS BETWEEN 90 AND 100 THEN "OUTSTANDING"
WHEN MARKS BETWEEN 80 AND 89 THEN "EXCELLENT"
WHEN MARKS BETWEEN 70 AND 79 THEN "VERYGOOD"
WHEN MARKS BETWEEN 60 AND 69 THEN "GOOD"
WHEN MARKS BETWEEN 50 AND 59 THEN "PASS"
ELSE "FAIL"
END AS REMARK
FROM STUDENT;

