CREATE DATABASE LIBRARYDB;
USE LIBRARYDB;

CREATE TABLE BOOKS(
BOOK_ID INT,
TITLE VARCHAR(100),
AUTHOR VARCHAR(50),
GENERE VARCHAR(50),
PUBLICATION_YEAR INT,
PRICE DECIMAL(8,2)
);

INSERT INTO BOOKS VALUES
(1,'THE GREAT LEADER','SCOTT','FICTION',1925,15.99),
(2,'TO KILL BIRD','HARPER','FICTION',1960,12.50),
(3,'THE FUTURE','GEORGE','DYSTIPIAN',1949,10.99),
(4,'IKI GAI','DONGLEE','FICTION',1951,14.75);

SELECT * FROM BOOKS;

-- ARTHMETIC OPERATOR

UPDATE BOOKS SET PRICE =PRICE+5.00;
SELECT * FROM BOOKS;

UPDATE BOOKS 
SET PRICE=PRICE-3.00
WHERE PUBLICATION_YEAR<1960;
SELECT * FROM BOOKS;

UPDATE BOOKS
SET PRICE=PRICE*2
WHERE GENERE='FICTION';
SELECT * FROM BOOKS;

UPDATE BOOKS
SET PRICE=PRICE/2
WHERE GENERE='FICTION';
SELECT * FROM BOOKS;

SELECT 10/3;

UPDATE BOOKS
SET PRICE=9.99
WHERE BOOK_ID %2=0;
SELECT * FROM BOOKS;

-- COMPARISION OPERATOR
SELECT * FROM BOOK
WHERE PUBLICATION_YEAR=1960;
SELECT * FROM BOOK
WHERE PUBLICATION_YEAR!=1960;
SELECT * FROM BOOK
WHERE PRICE<15;
SELECT * FROM BOOK
WHERE PRICE>15;
SELECT * FROM BOOK
WHERE PUBLICATION_YEAR<=1960;
SELECT * FROM BOOK
WHERE PUBLICATION_YEAR>=1960;

-- LOGICAL OPERATOR
SELECT * FROM BOOKS
WHERE GENERE ='FICTION' AND PRICE>15.00;

SELECT * FROM BOOKS
WHERE GENERE ='DYSTOPIAN' AND GENERE='COMEDY';

SELECT * FROM BOOKS
WHERE NOT GENERE ='FICTION';

-- SPECIAL OPERATORS

SELECT * FROM BOOKS
WHERE PUBLICATION_YEAR BETWEEN 1950 AND 1960;
SELECT * FROM BOOKS
WHERE PUBLICATION_YEAR NOT BETWEEN 1950 AND 1960;
SELECT * FROM BOOKS
WHERE GENERE IN ('FICTION','COMEDY');
SELECT * FROM BOOKS
WHERE GENERE NOT IN ('FICTION','COMEDY');
SELECT * FROM BOOKS
WHERE PUBLICATION_YEAR IS NULL;
SELECT * FROM BOOKS
WHERE PUBLICATION_YEAR IS NOT NULL;





