CREATE DATABASE TASK1;
USE TASK1;

CREATE TABLE EMPLOYEES(
EMPLOYEEID VARCHAR(5) PRIMARY KEY NOT NULL,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50)  UNIQUE NOT NULL,
PHONENUMBER BIGINT UNIQUE,
HIREDATE DATE NOT NULL,
JOBTITLE VARCHAR(30) NOT NULL,
DEPARTMENTID INT  NOT NULL,
SALARY DECIMAL(10,2) CHECK (SALARY > 0),
WORKINGSTATUS VARCHAR(20),
MANAGERNAME VARCHAR(30)
);

 -- DROP TABLE EMPLOYEES;


INSERT INTO EMPLOYEES 
(EMPLOYEEID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, HIREDATE, JOBTITLE, DEPARTMENTID, SALARY, WORKINGSTATUS ,MANAGERNAME)
VALUES
('E001','VINODH','PALLI','vinodh@gmail.com',7995231195,'2026-04-01','MANAGER',1,70000,'WORKING','SRIHARI'),
('E002','DURGA','KAGITHALA','durga@gmail.com',9876543211,'2026-04-01','ACCOUNTANT',2,60000,'WORKING','MANOHAR'),
('E003','CHANDU','DASARI','chandu@gmail.com',9567387654,'2024-04-01','DA',3,65000,'WORKING','RAHUL'),
('E004','KAIF','MOHAMAD','kaif@gmail.com',7568943276,'2024-04-01','MANAGER',1,70000,'WORKING','SRIHARI'),
('E005','SANATH','SURYA','sanath@gmail.com',6453728190,'2020-04-01','ACCOUNTANT',2,60000,'OLD EMPLOYEE','MANOHAR'),
('E006','RAM','KAMODULA','ram@gmail.com',7658493097,'2026-04-01','DA',3,65000,'WORKING','RAHUL'),
('E007','SRIDHAR','DUNNA','sridhar@gmail.com',9003408793,'2020-04-01','MANAGER',1,70000,'OLD EMPLOYEE','SRIHARI'),
('E008','SAI','PALLI','sai@gmail.com',6309803879,'2020-04-01','DA',3,67000,'OLD EMPLOYEE','RAHUL'),
('E009','PRABHA','IJJADA','prabha@gmail.com',9957634633,'2026-04-01','ACCOUNTANT',2,70000,'WORKING','MANOHAR'),
('E010','PRAKASH','PALLI','prakash@gmail.com',7597809352,'2021-04-01','ACCOUNTANT',2,65000,'OLD EMPLOYEE','MANOHAR');


-- CREATE DEPARTMENT TABLE
CREATE TABLE DEPARTMENT(
DEPARTMENTID INT PRIMARY KEY NOT NULL,
DEPARTMENTNAME VARCHAR(30) NOT NULL,
DEPTSTATUS VARCHAR(20) NOT NULL,
LOCATION VARCHAR(30) NOT NULL
);

-- DROP TABLE DEPARTMENT;

INSERT INTO DEPARTMENT( DEPARTMENTID ,DEPARTMENTNAME,DEPTSTATUS ,LOCATION )
VALUES
(1,'HR','ACTIVE','HYDERABAD'),
(2,'FINANCE','ACTIVE','HYDERABAD'),
(4,'MARKETING','NOT ACTIVE','BANGLORE'),
(3,'IT','ACTIVE','HYDERABAD'),
(5,'HUMAN RESOURSE','NOT ACTIVE','MUMBAI');

-- HIGHEST SALARY
SELECT FIRSTNAME,SALARY
FROM EMPLOYEES
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);

-- AVERAGE SALARY BY DEPARTMENT

SELECT DEPARTMENTID, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENTID;

-- EMPLOYEE SALARY IS GRETAER THAN AVERAGE SALARY 

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENTID IN (
SELECT DEPARTMENTID 
FROM EMPLOYEES
GROUP BY DEPARTMENTID 
HAVING AVG(SALARY) > 50000
);


-- Employees with same salary & department

SELECT E1.EMPLOYEEID, E1.FIRSTNAME,E1.SALARY
FROM EMPLOYEES E1
WHERE EXISTS (
SELECT 1
FROM EMPLOYEES E2
WHERE E1.DEPARTMENTID= E2.DEPARTMENTID
AND E1.SALARY = E2.SALARY
AND E1.EMPLOYEEID <> E2.EMPLOYEEID
);


-- 
SELECT *
FROM  EMPLOYEES E1
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM   EMPLOYEES E2
    WHERE E1.DEPARTMENTID= E2.DEPARTMENTID
);


-- Employees who joined earliest in their department

SELECT *
FROM EMPLOYEES E1
WHERE HIREDATE = (
SELECT MIN(HIREDATE)
FROM  EMPLOYEES E2
WHERE  E1.DEPARTMENTID= E2.DEPARTMENTID
);

-- JOINS
-- INNER JOIN
SELECT E.EMPLOYEEID,E.FIRSTNAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENT D
ON E.DEPARTMENTID= D.DEPARTMENTID;

-- LEFTJOIN
SELECT E.FIRSTNAME ,D.DEPARTMENTNAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENT D
ON E.DEPARTMENTID= D.DEPARTMENTID;

-- RIGHTJOIN
SELECT D.DEPARTMENTNAME,E.FIRSTNAME 
FROM DEPARTMENT D
LEFT JOIN  EMPLOYEES E
ON E.DEPARTMENTID= D.DEPARTMENTID;

-- CROSSJOIN
SELECT E.EMPLOYEEID,E.FIRSTNAME,D.DEPARTMENTNAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENT D;

-- SELFJOIN
SELECT 
E1.EMPLOYEEID AS EMP1_ID,
E1.FIRSTNAME AS EMP1_NAME,
E2.EMPLOYEEID AS EMP2_ID,
E2.FIRSTNAME AS EMP1_NAME,
E1.DEPARTMENTID
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON  E1.DEPARTMENTID =  E2.DEPARTMENTID
AND E1.EMPLOYEEID  < E2.EMPLOYEEID ;
    
-- INNER JOIN 
SELECT E.EMPLOYEEID AS EMP_ID,
E.FIRSTNAME AS EMP_NAME,M.MANAGERNAME AS MANAGER_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
    ON e.manager_id = m.employee_id;
    
    
-- EMPLOYEES WITH ACTIVE DEPARTMENT
SELECT E.EMPLOYEEID,E.FIRSTNAME,D.DEPARTMENTNAME
FROM EMPLOYEES E
JOIN (
    SELECT DEPARTMENTID,DEPARTMENTNAME
    FROM DEPARTMENT
    WHERE DEPTSTATUS = 'ACTIVE'
) D
ON E.DEPARTMENTID = D.DEPARTMENTID;

-- EMPLOYEES EARNING ABOVE DEPARTMENT AVERAGE SALARY

SELECT 
E.EMPLOYEEID,
E.FIRSTNAME,
E.SALARY,
D.DEPARTMENTNAME
FROM EMPLOYEES E
JOIN (
SELECT 
DEPARTMENTID, 
AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENTID
) AVG_DEPT
ON E.DEPARTMENTID = AVG_DEPT.DEPARTMENTID
JOIN DEPARTMENT D
ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE E.SALARY > AVG_DEPT.AVG_SALARY;

-- 

SELECT D.DEPARTMENTNAME,COUNT(E.EMPLOYEEID) AS TOTAL_EMPLOYEES,
AVG(E.SALARY) AS AVG_SALARY
FROM DEPARTMENT D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;S









