CREATE DATABASE EMPLOYEEDB;
USE EMPLOYEEDB;

CREATE TABLE EMPLOYEES(
EMPID INT PRIMARY KEY,
EMPNAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY DECIMAL(10,2)
);

INSERT INTO EMPLOYEES VALUES
(101,'A','IT',50000),
(102,'B','HR',40000),
(103,'C','IT',60000),
(104,'D','FINANCE',45000),
(105,'E','IT',55000);

-- CREATE STRE PROCUDURE TOTAL SALRY BY DEPARTMENT
DELIMITER //
CREATE PROCEDURE TOTALSALARY (IN DEPT_NAME VARCHAR(50))
BEGIN
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT=DEPT_NAME
GROUP BY DEPARTMENT;
END//
DELIMITER ;
CALL TOTALSALARY('IT');
CALL TOTALSALARY('HR');
CALL TOTALSALARY('SALES');

-- CREATE PROCUDRE TO UPDAT SALRY OF DEPARTMENTS
DELIMITER //
CREATE PROCEDURE UPDATEDEPTSALARIES(
IN DEPT_NAME VARCHAR(50),
IN INCREAMENT DECIMAL(10,2)
)
BEGIN 
UPDATE EMPLOYEES
SET SALARY=SALARY + INCREAMENT
WHERE DEPARTMENT=DEPT_NAME;

SELECT EMPID,EMPNAME,DEPARTMENT,SALARY
FROM EMPLOYEES
WHERE DEPARTMENT=DEPT_NAME;
END //
DELIMITER ; 

-- DROP PROCEDURE UPDATEDEPTSALARIES;

CALL UPDATEDEPTSALARIES('IT',5000.00);


