-- AGGREGATE FUNCTIONS
CREATE DATABASE CODB;
USE CODB;
CREATE TABLE EMPL(
EMPID INT PRIMARY KEY,
EMPNAME VARCHAR(50),
DEPT VARCHAR(30),
SALARY DECIMAL(10,2)
);

INSERT INTO EMPL VALUES
(101,'JOHN','HR',50000.00),
(102,'AMAN','FINANCE',60000.00),
(103,'BOB','IT',55000),
(104,'DAVID','HR',52000),
(105,'EESHA','FINANCE',62000),
(106,'FRANK','IT',58000),
(107,'GRACE','FINANCE',61000),
(108,'RAVI','IT',57000);

SELECT * FROM EMPL;

-- count -- count toatal employees

SELECT COUNT(*) AS TOTALEMPLOYEES
FROM EMPL;

-- SUM -- TOTAL SALARY OF ALL EMPLOYES

SELECT SUM(SALARY) AS TOTALSALARY FROM EMPL;

-- AVG -- AVERAGE SALARY 
SELECT AVG(SALARY) AS AVERAGESALARY FROM EMPL;

-- MIN() -- LOWEST SALARY
SELECT MIN(SALARY) AS MINIMUMSALARY FROM EMPL;

-- MAX() -- HEIGHEST SALARY
SELECT MAX(SALARY) AS MINIMUMSALARY FROM EMPL;

-- GROUP BY CLAUSE
-- NUMBER OF EMPLOYEES IN EACH DEPARTMENT
SELECT DEPT,COUNT(*) AS EMPLOYEESCOUNT
FROM EMPL
GROUP BY DEPT;

-- TOTAL SALARY
SELECT DEPT,SUM(SALARY) AS TOTALSALRY
FROM EMPL
GROUP BY DEPT;

-- AVEAGE SALARY
SELECT DEPT,AVG(SALARY) AS AVERAGESALARY
FROM EMPL
GROUP BY DEPT;

-- MINUMUM SALARY
SELECT DEPT,MIN(SALARY) AS LOWSALARY
FROM EMPL
GROUP BY DEPT;

-- MAX SALARY
SELECT DEPT,MAX(SALARY) AS HEIGHESTSALARY
FROM EMPL
GROUP BY DEPT;

-- HAVING 
-- SHOW ONLY DEPARTMENTS WHERE AVERAGE SALARY >55000


-- AVEAGE SALARY
SELECT DEPT,AVG(SALARY) AS AVGSALARY
FROM EMPL
GROUP BY DEPT
HAVING AVG(SALARY)>55000;

-- SHOW ONLY DEPARTMENTS WHERE SUM OF SALARY >150000

-- TOTAL SALARY
SELECT DEPT,SUM(SALARY) AS TOTALSALRY
FROM EMPL
GROUP BY DEPT
HAVING SUM(SALARY)>150000;


