CREATE DATABASE SUBQUERY;
USE SUBQUERY;

CREATE TABLE EMPLOYEES(
EMPID INT PRIMARY KEY,
EMPNAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY INT 
);

INSERT INTO EMPLOYEES VALUES
(1,'A','HR',50000),
(2,'B','IT',60000),
(3,'C','FINANCE',55000),
(4,'D','IT',65000),
(5,'E','FINANCE',70000);

-- SCALAR SUBQUERY
-- FIND EMPLOYEES HEIGHEST SALARY

SELECT EMPNAME,SALARY
FROM EMPLOYEES
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);

-- MULTIPLE ROW QUERY
-- FIND EMPLOYEES WHO WORKS SAME DEPART MENT AS E 
SELECT EMPNAME,DEPARTMENT
FROM EMPLOYEES
WHERE DEPARTMENT IN (
SELECT DEPARTMENT
FROM EMPLOYEES
WHERE EMPNAME='E');

-- CORELATED SUBQUERY

SELECT EMPNAME,DEPARTMENT,SALARY
FROM EMPLOYEES E
WHERE SALARY>(
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT=E.DEPARTMENT
);

-- DERIVED TABLE 

-- CALUCLATE AVG SALARY ,THEN GET DEPARTMENTS WITH AVG SAL>60000

SELECT DT.DEPARTMENT ,DT.AVGSAL
FROM (
SELECT DEPARTMENT,AVG(SALARY) AS AVGSAL
FROM EMPLOYEES
GROUP BY DEPARTMENT
)AS DT
WHERE DT.AVGSAL>60000;

-- CTE
-- CREATE CTE NAMED DEPTAVG TO CALUCLATE AVG SALRY PER DEPT

WITH DEPTAVG AS(
SELECT DEPARTMENT,AVG(SALARY) AS AVGSAL
FROM EMPLOYEES
GROUP BY DEPARTMENT
)
SELECT * FROM DEPTAVG
WHERE AVGSAL>60000;

-- VIEWS 
CREATE VIEW HIGHSALARYEMPLOYEES AS
SELECT * FROM EMPLOYEES
WHERE SALARY>60000;

SELECT * FROM HIGHSALARYEMPLOYEES;

INSERT INTO EMPLOYEES VALUES
(6,'F','MARKETING',80000);

SELECT * FROM HIGHSALARYEMPLOYEES;

UPDATE EMPLOYEES
SET SALARY=90000
WHERE EMPNAME='A';

SELECT * FROM HIGHSALARYEMPLOYEES;

-- DROP VIEW VIEWNAME
