CREATE DATABASE SETOPERATIONS;
USE SETOPERATIONS;

CREATE TABLE DEPTA(
EMPID INT PRIMARY KEY,
FNAME  VARCHAR(50)
);

CREATE TABLE DEPTB(
EMPID INT PRIMARY KEY,
FNAME  VARCHAR(50)
);

INSERT INTO DEPTA VALUES
(1,'JOHN'),(2,'JAMES'),(3,'BOB');

INSERT INTO DEPTB VALUES
(3,'BOB'),(4,'MARK'),(5,'MARY');

SELECT EMPID,FNAME FROM DEPTA
UNION 
SELECT EMPID,FNAME FROM DEPTB; 


SELECT EMPID,FNAME FROM DEPTA
UNION ALL
SELECT EMPID,FNAME FROM DEPTB; 

