CREATE DATABASE EMPDB;
USE EMPDB;

CREATE TABLE STUDENT(
ID INTEGER,
FIRSTNAME TEXT NOT NULL,
LASTNAME TEXT NOT NULL
);

DESC STUDENT;

INSERT INTO STUDENT VALUES(1,'PETER','HANKS');
INSERT INTO STUDENT VALUES(1,NULL,'HANKS');
INSERT INTO STUDENT VALUES(NULL,'A','B');
DESC STUDENT;

SELECT * FROM STUDENT;

-- DEFAULT

CREATE TABLE PERSONS(
ID INT NOT NULL,
NAME VARCHAR(45),
CITY VARCHAR(20) DEFAULT 'NEWYORK'
);

DESC PERSONS;

INSERT INTO PERSONS(ID,NAME,CITY)
VALUES(1,'A','HYD');

INSERT INTO PERSONS(ID,NAME)
VALUES(2,'B');

SELECT * FROM PERSONS;

INSERT INTO PERSONS(ID,NAME,CITY)
VALUES(3,'C','VIJ');

-- PRIMARY KEY

CREATE TABLE PERSONS1(
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(45),
AGE INT,
CITY VARCHAR(25)
);

INSERT INTO PERSONS1 VALUES
(1,'A',24,'HYD'),(2,'B',23,'BEN');

SELECT * FROM PERSONS1;

-- UNIQUE KEY

CREATE TABLE EMPLOYEES(
ID INT PRIMARY KEY,
EMAIL VARCHAR(100),
PHONE VARCHAR(20),
UNIQUE (EMAIL),
UNIQUE(PHONE)
);

 INSERT INTO EMPLOYEES VALUES
 (1,'A@ABC.COM','123456789');
 
 INSERT INTO EMPLOYEES VALUES
 (2,'B@ABC.COM','7995233595');
 
 INSERT INTO EMPLOYEES VALUES
 (3,'3@ABC.COM','9000340889');
 
 INSERT INTO EMPLOYEES VALUES
 (4,NULL,'96341758129');
 
 SELECT * FROM EMPLOYEES;
 
 -- AUTO_INCREMENT
 CREATE TABLE ANIMALS(
 ID INT NOT NULL AUTO_INCREMENT,
 NAME CHAR (30) NOT NULL,
 PRIMARY KEY(ID)
 );
 
 DESC ANIMALS;
 
 INSERT INTO ANIMALS(NAME)
 VALUES('CAT'),('DOG'),('HORSE'),('LION'),('TIGER');
 
 SELECT * FROM ANIMALS;
 
 -- check 
 CREATE TABLE EMP(
 ID INT NOT NULL,
 NAME VARCHAR(45) NOT NULL,
 AGE INT CHECK (AGE>=18) ); -- AGE MUST BE 18 ABOVE 
 
 DESC EMP;
 
  INSERT INTO EMP VALUES
  (1,'A',19),(2,'B',24);
  
  SELECT * FROM EMP;
  
  -- FOREIGN KEY
  CREATE TABLE DEPARTMENTS(
  DEPTID INT PRIMARY KEY,
  DEPTNAME VARCHAR(50)
  );
  
  INSERT INTO DEPARTMENTS 
  VALUES (1,'HR'),(2,'IT'),(3,'FINANCE');
  
  CREATE TABLE EMP2(
  EMPID INT PRIMARY KEY,
  EMPNAME VARCHAR(50),
  DEPTID INT,
  FOREIGN KEY (DEPTID) REFERENCES DEPARTMENTS(DEPTID)
  );
  
  INSERT INTO  EMP2 VALUES
  (101,'A',1),
  (102,'B',2),
  (103,'C',3);
  
  INSERT INTO EMP2 VALUES
  (104,'D',4);
 
 -- COMPOSITE KEY
 
 CREATE TABLE STUDENT_COURSES(
 STUDENT_ID INT,
 COURSE_ID INT,
 GRADE CHAR(1),
 PRIMARY KEY(STUDENT_ID,COURSE_ID)-- COMPOSITE KEY
 );
 
 INSERT INTO STUDENT_COURSES(STUDENT_ID,COURSE_ID,GRADE)
 VALUES (1,101,'A'),(1,102,'B'),(2,101,'C');
 
 SELECT *FROM STUDENT_COURSES; 
 
 INSERT INTO STUDENT_COURSES(STUDENT_ID,COURSE_ID,GRADE)
 VALUES (1,101,'D');
 
 






