CREATE DATABASE STUDENTDB;
USE STUDENTDB;

CREATE TABLE STUDENTS(
STUDENTID INT PRIMARY KEY AUTO_INCREMENT,
STUDENTNAME CHAR(30) NOT NULL,
AGE  INT CHECK (AGE>=18),
EMAIL VARCHAR(50) UNIQUE,
COURSE VARCHAR(20) DEFAULT 'GENERAL',
MARKS INT CHECK (marks BETWEEN 0 AND 100)
);

INSERT INTO STUDENTS (STUDENTNAME,AGE,EMAIL,MARKS)
VALUES('VINODH',22,'VINODH@gmail.com',99),
('DURGA',23,'DURGA@gamil.com',98),
('CHANDU',23,'CHANDU@gamil.com',95),
('KAIF',21,'KAIF@gamil.com',75),
('SANATH',25,'SANATH@gmail.com',64);

SELECT * FROM STUDENTS;

SELECT * FROM STUDENTS
WHERE MARKS>70 AND AGE<25;


SELECT * FROM STUDENTS
WHERE COURSE!='GENERAL';

SELECT * FROM STUDENTS
WHERE MARKS BETWEEN 50 AND 80;

SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE 'A%';

SELECT * FROM STUDENTS
WHERE EMAIL LIKE '%gmail%' ;

SELECT * FROM STUDENTS ORDER BY MARKS DESC;

SELECT * FROM STUDENTS LIMIT 5; 

SELECT DISTINCT COURSE FROM STUDENTS;

SELECT COURSE,COUNT(STUDENTNAME) AS NUMBEROFSTUDENTS
FROM STUDENTS
GROUP BY COURSE;

SELECT COURSE,COUNT(STUDENTNAME) AS NUMBEROFSTUDENTS
FROM STUDENTS
GROUP BY COURSE
HAVING COUNT(COURSE)>2;







 