-- ORDER OF EXECUTION 
USE COMPANYDB;

CREATE TABLE EMPLOY(
EMPID INT PRIMARY KEY,
EMPNAME VARCHAR(50),
DEPARTMENT VARCHAR(30),
AGE INT,
SALARY DECIMAL(10,2)
);

INSERT INTO EMPLOY VALUES
(1, 'JOHN', 'HR', 28, 40000),
(2, 'MARY', 'HR', 32, 42000),
(3, 'STEVE', 'IT', 26, 50000),
(4, 'AMAN', 'IT', 31, 52000),
(5, 'BOB', 'FINANCE', 29, 41000),
(6, 'EESHA', 'FINANCE', 29, 41000),
(7, 'TOM', 'IT', 27, 49000),
(8, 'SARA', 'HR', 30, 43000),
(9, 'RAJ', 'FINANCE', 33, 45000),
(10, 'NAINA', 'IT', 35, 55000);

SELECT * FROM EMPLOY;

-- I WANT TO KNOW WHICH DEPARTMENTS HAVE MORE THAN 2 EMPLOYEES
-- BUT ONLY CONSIDER EMPLOYEES OLDER THAN25
-- AND ALSO JUST SHOW ME THE FIRST 2 DEPARTMENTS IN ALPHABETICAL ORDER
-- ALSO IF BY CHANCE ANY DEPARTNEBT NAMES REPEAT SHOW IT ONLY ONCE

SELECT DISTINCT DEPARTMENT ,COUNT(*) AS TOTAL_EMPLOYEE
FROM  EMPLOY
WHERE AGE > 25
GROUP BY DEPARTMENT 
HAVING COUNT(*)>2
ORDER BY DEPARTMENT 
LIMIT 2;

SELECT  DISTINCT DEPARTMENT,AVG(SALARY) AS AVGSALARY
FROM EMPLOY
WHERE AGE>27
GROUP BY DEPARTMENT
HAVING AVG(SALARY)>42000
ORDER BY DEPARTMENT ASC
LIMIT 2; 