CREATE DATABASE STRDB;
USE STRDB;

CREATE TABLE EMPLOYEES(
EMPID INT,
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(30),
DEPARTMENT VARCHAR(30),
CITY VARCHAR(30)
);

INSERT INTO EMPLOYEES VALUES
(1,'JOHN','SMITH','SALES','NEWYORK'),
(2,'RAVI','KUMAR','FINANCE','LONDON'),
(3,'ROBERT','TYLOR','IT','SYDNEY'),
(4,'EMMA','WATSON','HR','TORANTO'),
(5,'DAVID','CLARK','MARKETING','PARIS');

SELECT * FROM EMPLOYEES;

-- CONCAT()

SELECT EMPID,CONCAT(FIRSTNAME,' ',LASTNAME) AS FULLNAME
FROM EMPLOYEES;

-- CONCAT_WS
SELECT EMPID,CONCAT_WS('-',FIRSTNAME,LASTNAME,DEPARTMENT)AS DETAILS
FROM EMPLOYEES;

-- LENGTH()

SELECT FIRSTNAME,LENGTH(FIRSTNAME) AS NAMELENGTH
FROM EMPLOYEES;
SELECT LENGTH('❤');

-- CHARLENGTH
SELECT FIRSTNAME,CHAR_LENGTH(FIRSTNAME) AS NAMELENGTH
FROM EMPLOYEES;

SELECT CHAR_LENGTH('❤');

-- LOWER()/LCASE()

SELECT LOWER(DEPARTMENT) AS LOWERDEPT,
LCASE(CITY) AS LOWERCITY
FROM EMPLOYEES;

-- UPPER()/UCASE()

SELECT UPPER(DEPARTMENT) AS UPPERDEPT,
UCASE(CITY) AS UPPERCITY
FROM EMPLOYEES;

-- SUBSTRING()/ SUBSTR()

SELECT FIRSTNAME ,
SUBSTRING(FIRSTNAME,1,3) AS SHORTNAME,
SUBSTR(LASTNAME,2,4) AS LASTPART
FROM EMPLOYEES;

-- INSTR

SELECT DEPARTMENT,
INSTR(DEPARTMENT,'A') AS POSTIONOFA
FROM EMPLOYEES;

SELECT INSTR("HELLO WORLD","WORLD") AS POSITIONOFW;

-- LEFT() AND RIGHT()
SELECT FIRSTNAME,
LEFT(FIRSTNAME,2) AS LEFTCHARS,
RIGHT(FIRSTNAME,2) AS RIGHTCHARS
FROM EMPLOYEES;

-- REVERSE

SELECT FIRSTNAME,REVERSE(FIRSTNAME) AS REVERSED
FROM EMPLOYEES;

-- REPLACE

SELECT DEPARTMENT,REPLACE(DEPARTMENT,'A','@') AS MODIFIED
FROM EMPLOYEES;

SELECT REPLACE('HELLO WORLD','WORLD','MYSQL')  AS REPLACED;

-- TRIM()

SELECT TRIM('   MYSQL ') AS TRIMED;
SELECT TRIM(LEADING 'A'FROM 'AAAAHELLO') AS LEADTRIMED;
SELECT TRIM(TRAILING 'A'FROM 'HELLOAAAA') AS TRAILTRIMED;
SELECT TRIM(BOTH 'A'FROM 'AAAAHELLOAAAAAA') AS BOTHTRIMED;