create database TRIGERDB;
USE TRIGERDB;
CREATE TABLE EMPLOYEE(
EMPID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY DECIMAL(10,2),
PENDINGINVOICE DECIMAL(10,2) DEFAULT 0
);

CREATE TABLE EMPLOYEE_LOG(
LOGID INT AUTO_INCREMENT PRIMARY KEY,
EMPID INT,
ACTIONTYPE VARCHAR(50),
OLDSALARY DECIMAL(10,2),
NEWSALARY DECIMAL(10,2),
LOGTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO EMPLOYEE VALUES
(1,'RAVI',50000,2000),
(2,'RAJU',30000,0),
(3,'KIRAN',45000,0);

-- BEFORE INSERT,

DELIMITER //
CREATE TRIGGER BEFORE_INSERT_EMP
BEFORE INSERT ON EMPLOYEE FOR EACH ROW
BEGIN
IF NEW.SALARY<0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT ='SALARY CANNOT BE NEGATIVE';
END IF;
END//
DELIMITER ;

-- DROP TRIGGER BEFORE_INSERT_EMP;

-- AFTER INSERT

DELIMITER //
CREATE TRIGGER AFTER_INSERT_EMP
AFTER INSERT ON EMPLOYEE FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_LOG(EMPID,ACTIONTYPE,NEWSALARY)
VALUES
(NEW.EMPID,'INSERTED',NEW.SALARY);
END //
DELIMITER ;

-- TEST 
INSERT INTO EMPLOYEE VALUES(4,'ARUN',-20000,0);
INSERT INTO EMPLOYEE VALUES(4,'ARUN',20000,0);

SELECT * FROM EMPLOYEE_LOG;

-- BEFORE UPDATE
-- SALARY SHOULD BE INCREES CNNOT EXCEEDS 80%

DELIMITER //
CREATE TRIGGER BEFORE_UPDATE_EMP
BEFORE UPDATE ON EMPLOYEE FOR EACH ROW 
BEGIN
IF NEW.SALARY>OLD.SALARY*1.8 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT='SALARY INCERASE CANNOT EXCEED 80%';
END IF ;
END //
DELIMITER ; 

-- AFTER UPDATE
DELIMITER //
CREATE TRIGGER AFTER_UPDATE_EMP
AFTER UPDATE ON EMPLOYEE FOR EACH ROW 
BEGIN
INSERT INTO EMPLOYEE_LOG(EMPID,ACTIONTYPE,OLDSALARY,NEWSALARY)
VALUES
(OLD.EMPID,'UPDATE',OLD.SALARY,NEW.SALARY);
END //
DELIMITER ; 

-- TEST
UPDATE EMPLOYEE
SET SALARY =100000
WHERE EMPID=1;

UPDATE EMPLOYEE
SET SALARY = 30000
WHERE EMPID=1;

SELECT * FROM EMPLOYEE_LOG;

-- BEFORE DELETE 
DELIMITER //
CREATE TRIGGER BEFORE_DELETE_EMP
BEFORE DELETE ON EMPLOYEE FOR EACH ROW
BEGIN
IF OLD.PENDINGINVOICE > 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT ='CANNOT DELETE EMPLOYEES IF PENDING INOICE EXISTS';
END IF;
END//
DELIMITER ;

-- AFTER DELETE

DELIMITER //
CREATE TRIGGER AFTER_DELETE_EMP
AFTER DELETE ON EMPLOYEE FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_LOG(EMPID,ACTIONTYPE,NEWSALARY)
VALUES
(OLD.EMPID,'DELETED',OLD.SALARY);
END //
DELIMITER ;

SELECT * FROM EMPLOYEE;

-- TEST
DELETE FROM EMPLOYEE WHERE EMPID=1;
DELETE FROM EMPLOYEE WHERE EMPID=3;

-- --------------------------



 

