SHOW DATABASES;

CREATE DATABASE COMPANYDB;

SHOW DATABASES;

USE COMPANYDB;

CREATE TABLE EMPLOYEES(
EMP_ID CHAR(5),
FNAME VARCHAR(50),
LANME VARCHAR(50),
AGE INT,
DOJ DATE,
ADDRESS TINYTEXT,
DEPT VARCHAR(20)
);

SHOW TABLES;

DESC EMPLOYEES;

SHOW COLUMNS FROM EMPLOYEES;

-- ALTER  -- COMMENT

ALTER TABLE EMPLOYEES 
MODIFY FNAME VARCHAR(30);

DESC EMPLOYEES;

ALTER TABLE EMPLOYEES
ADD LOCATION TINYTEXT;

SHOW COLUMNS FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
ADD PFID INT AFTER AGE;

ALTER TABLE EMPLOYEES 
ADD SAL_COD INT FIRST;

-- RENAME COLUMN NAME

ALTER TABLE EMPLOYEES
RENAME COLUMN FNAME TO FIRSTNAME;

ALTER TABLE EMPLOYEES
CHANGE COLUMN LANME LASTNAME VARCHAR(30);

DESC EMPLOYEES;

-- DROP DATBASE COMPANYDB;
-- DROP TABLE EMPLOYEES;

ALTER TABLE EMPLOYEES
DROP COLUMN PFID;

ALTER TABLE EMPLOYEES
DROP COLUMN SAL_COD;

ALTER TABLE  EMPLOYEES
DROP COLUMN LOCATION;

ALTER TABLE EMPLOYEES
RENAME EMP;

INSERT INTO EMP(EMP_ID, FIRSTNAME,LASTNAME,AGE,DOJ,ADDRESS,DEPT)
VALUES
('E001','JOHN','DOE',30,'2023-01-01','123 MAIN ST','IT'),
('E002','JANE','SMITH',25,'2023-02-15','456 OAK ST','HR'),
('E003','BOB','JOHNSON',35,'2022-12-10','789 PINE ST','FINANCE');

SELECT * FROM EMP;

TRUNCATE TABLE EMP;

-- UPDATE

UPDATE EMP
SET ADDRESS='259 SPK ST'
WHERE EMP_ID='E001';

UPDATE EMP
SET DEPT='SALES'
WHERE EMP_ID='E003';
SELECT * FROM EMP;

-- DELETE

DELETE FROM EMP
WHERE EMP_ID='E001';

SELECT * FROM EMP;

DELETE FROM EMP
WHERE AGE>=30;
DELETE FROM EMP;

SELECT * FROM EMP; 

-- lock

SELECT *FROM EMP;

-- LOCK THE TABLE (NO OTHER USER CAN MODIFY)
LOCK TABLE EMP WRITE;

UPDATE EMP 
SET AGE=30
WHERE EMP_ID='E002';
COMMIT;
UNLOCK TABLES;

SELECT * FROM EMP;
LOCK TABLE EMP READ;
SELECT * FROM EMP;
COMMIT;


