CREATE DATABASE IRISDB;
USE IRISDB;

CREATE TABLE IRIS (
SEPALLENGTH FLOAT NOT NULL,
SEPALWIDTH FLOAT NOT NULL,
PETALLENGTH FLOAT NOT NULL,
PETALWIDTH FLOAT NOT NULL,
SPECIES VARCHAR(50) NOT NULL
);

SELECT * FROM IRIS;

-- VIEW FIRST 10 ROWS FROM IRIS DATASET
SELECT * FROM IRIS 
LIMIT 10;

-- GET ALL UNIQUE SPECIES NAMES FROM THE DATASET
SELECT DISTINCT SPECIES
FROM IRIS;

-- COUNT HOW MANY RECORED BELONG TOEACH SPECHIES
SELECT SPECIES,COUNT(*) AS COUNT
FROM IRIS 
GROUP BY SPECIES;

-- SHOW TOP 5 ROW WITH LARGEST SEPAL LENGTH
SELECT * FROM IRIS 
ORDER BY SEPALLENGTH DESC;

USE PYTHONDB;

SELECT * FROM EMPLOYEES

